---
version: "3"

services:
  portmap-server:
    image: dmotte/portmap-server
    build: build
    restart: always
    network_mode: bridge
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ssh-host-keys:/ssh-host-keys
      - ./volumes/ssh_client_key.pub:/ssh-client-keys/ssh_client_key.pub:ro
    ports:
      - "80:8080"
      - "2222:22"

volumes:
  ssh-host-keys: {}
