---
version: "3"

services:
  portmap-server:
    image: dmotte/portmap-server
    build: build
    restart: always
    network_mode: bridge
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Host keys
      - ./volumes/ssh_host_ecdsa_key:/etc/ssh/ssh_host_ecdsa_key:ro
      - ./volumes/ssh_host_ecdsa_key.pub:/etc/ssh/ssh_host_ecdsa_key.pub:ro
      - ./volumes/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - ./volumes/ssh_host_ed25519_key.pub:/etc/ssh/ssh_host_ed25519_key.pub:ro
      - ./volumes/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
      - ./volumes/ssh_host_rsa_key.pub:/etc/ssh/ssh_host_rsa_key.pub:ro
      # Client's public key
      - ./volumes/ssh_client_key.pub:/authorized_keys/ssh_client_key.pub:ro
    ports:
      - "80:8080"
      - "2222:22"
